services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  stripe:
    image: stripe/stripe-cli:latest
    container_name: payment_gateway_stripe
    command: listen --forward-to host.docker.internal:8080/api/payments/webhook
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb:
  redis: